FROM node:20-alpine

ENV NODE_OPTIONS --max-old-space-size=4096

WORKDIR /app

RUN apk add --no-cache --virtual .gyp \
        python3 \
        make \
        g++

COPY package*.json ./

RUN npm install && apk del .gyp

COPY . .

CMD npm run migrate && npm run serve
