version: "3"

services:
  # ipfs:
  #   image: ipfs/go-ipfs
  #   ports:
  #     - "5001:5001/tcp"
  cassandra:
    restart: always
    image: cassandra
    env_file:
      - ./.env.development
    ports:
      - 9042:9042
  torus-metadata:
    restart: always
    depends_on:
      - cassandra
      # - ipfs
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "5051:5051/tcp"
    volumes:
      - .:/app
