services:
  # ipfs:
  #   image: ipfs/go-ipfs
  #   ports:
  #     - "5001:5001/tcp"
  redis:
    restart: always
    image: redis
    env_file:
      - ./.env.development
    ports:
      - "6379:6379"
  mysql:
    restart: always
    # platform: linux/x86_64
    image: mysql:8
    command: --max_allowed_packet=67108864 # 64 MB
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
  torus-metadata:
    restart: always
    depends_on:
      - mysql
      # - ipfs
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    ports:
      - "5051:5051/tcp"
    volumes:
      - .:/app
