FROM node:12-alpine

WORKDIR /app

COPY package*.json ./

ENV NODE_OPTIONS --max-old-space-size=4096

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        && npm install && apk del .gyp

COPY . .

CMD npm run migrate && npm run serve