services:
  # ipfs:
  #   image: ipfs/go-ipfs
  #   ports:
  #     - "5001:5001/tcp"
  redis:
    restart: always
    image: redis:6-alpine
    env_file:
      - ./.env.development
    ports:
      - "6379:6379"
    healthcheck:
      interval: 5s
      retries: 5
      test: redis-cli --raw incr ping
      timeout: 1s
  mysql:
    restart: always
    platform: linux/x86_64
    image: mysql:8
    env_file:
      - ./.env.development
    ports:
      - "3306:3306"
    healthcheck:
      interval: 5s
      retries: 5
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 1s
  torus-metadata:
    restart: "no"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      # - ipfs
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.development
    command: "/app/test/run.sh"
